name: 🏗 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: 📚 lint and type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: yarn
      - name: lint
        run: yarn test:linter
      - name: type check
        run: yarn test:type
